#include "espscreen/hal/audio_device.hpp"
#include "espscreen/hal/audio_signal.hpp"
#include "espscreen/hal/audio_buffer_plan.hpp"
#include "espscreen/hal/audio_hardware_plan.hpp"
#include "driver/ledc.h"
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "esp_heap_caps.h"
#include <algorithm>
#include <cstring>
namespace espscreen::hal {
AudioDevice::~AudioDevice(){stop();}
core::Status AudioDevice::start(){const auto plan=audio_hardware_plan(config_);if(!plan.valid()){health_={DeviceState::degraded,core::ErrorCode::unsupported,"audio configuration is unavailable or invalid"};return {core::ErrorCode::unsupported,"audio configuration is unavailable or invalid"};}health_.state=DeviceState::starting;core::Status s;switch(plan.startup){case AudioStartupKind::pwm:s=start_pwm();break;case AudioStartupKind::codec_i2s:s=start_es8311();break;case AudioStartupKind::direct_i2s:s=samples_.start();break;case AudioStartupKind::unavailable:s={core::ErrorCode::unsupported,"audio not configured"};break;}if(s&&plan.data_bus>=0)s=prepare_pcm_resources();if(s){tone_worker_running_=true;TaskHandle_t task{};if(xTaskCreate(&AudioDevice::tone_worker_entry,"ui_audio",4096,this,4,&task)!=pdPASS){tone_worker_running_=false;s={core::ErrorCode::unavailable,"audio worker allocation failed"};}else tone_task_=task;}if(!s)stop();health_=s.ok()?DeviceHealth{DeviceState::ready,core::ErrorCode::ok,"ready"}:DeviceHealth{DeviceState::degraded,s.code(),"audio initialization failed"};return s;}
core::Status AudioDevice::prepare_pcm_resources(){tone_buffer_=static_cast<std::int16_t*>(heap_caps_malloc(audio_buffer_plan.bytes(),MALLOC_CAP_8BIT));capture_buffer_=static_cast<std::int16_t*>(heap_caps_malloc(audio_buffer_plan.bytes(),MALLOC_CAP_8BIT));tx_mutex_=xSemaphoreCreateMutex();if(!tone_buffer_||!capture_buffer_||!tx_mutex_)return {core::ErrorCode::unavailable,"audio scratch allocation failed"};return core::Status::success();}
core::Status AudioDevice::start_pwm(){if(config_.pins.speaker<0)return {core::ErrorCode::unsupported,"speaker pin absent"};ledc_timer_config_t t{};t.speed_mode=LEDC_LOW_SPEED_MODE;t.timer_num=LEDC_TIMER_1;t.duty_resolution=LEDC_TIMER_10_BIT;t.freq_hz=1000;t.clk_cfg=LEDC_AUTO_CLK;if(ledc_timer_config(&t)!=ESP_OK)return {core::ErrorCode::io_error,"audio timer failed"};ledc_channel_config_t c{};c.gpio_num=config_.pins.speaker;c.speed_mode=LEDC_LOW_SPEED_MODE;c.channel=LEDC_CHANNEL_1;c.timer_sel=LEDC_TIMER_1;c.duty=0;if(ledc_channel_config(&c)!=ESP_OK)return {core::ErrorCode::io_error,"audio channel failed"};return core::Status::success();}
core::Status AudioDevice::start_es8311(){if(config_.pins.speaker>=0){gpio_set_direction(static_cast<gpio_num_t>(config_.pins.speaker),GPIO_MODE_OUTPUT);gpio_set_level(static_cast<gpio_num_t>(config_.pins.speaker),0);}if(const auto codec=codec_.start();!codec)return codec;return samples_.start();}
core::Status AudioDevice::tone(std::uint16_t hz,std::uint16_t duration,std::uint8_t volume){if(health_.state!=DeviceState::ready)return {core::ErrorCode::unavailable,"audio not ready"};volume=effective_volume(volume,volume_);if(config_.driver==board::AudioDriver::pwm){ledc_set_freq(LEDC_LOW_SPEED_MODE,LEDC_TIMER_1,hz);ledc_set_duty(LEDC_LOW_SPEED_MODE,LEDC_CHANNEL_1,pwm_duty(volume));ledc_update_duty(LEDC_LOW_SPEED_MODE,LEDC_CHANNEL_1);vTaskDelay(pdMS_TO_TICKS(duration));ledc_set_duty(LEDC_LOW_SPEED_MODE,LEDC_CHANNEL_1,0);ledc_update_duty(LEDC_LOW_SPEED_MODE,LEDC_CHANNEL_1);return core::Status::success();}if(!tx_mutex_||xSemaphoreTake(static_cast<SemaphoreHandle_t>(tx_mutex_),portMAX_DELAY)!=pdTRUE)return {core::ErrorCode::unavailable,"audio output lock unavailable"};const auto result=tone_i2s(hz,duration,volume);xSemaphoreGive(static_cast<SemaphoreHandle_t>(tx_mutex_));return result;}
core::Status AudioDevice::tone_i2s(std::uint16_t hz,std::uint16_t duration,std::uint8_t volume){
 if(const auto restarted=samples_.restart_output();!restarted)return restarted;
 if(config_.pins.speaker>=0)gpio_set_level(static_cast<gpio_num_t>(config_.pins.speaker),0);
 const std::size_t frames=tone_frame_count(config_.sample_rate,duration);std::size_t done=0;while(done<frames){const std::size_t n=std::min(audio_buffer_plan.frames,frames-done);render_stereo_sine(tone_buffer_,n,config_.sample_rate,hz,volume,done);auto s=write_pcm_unlocked(tone_buffer_,n);if(!s)return s;done+=n;}
 // The I2S peripheral repeats the final DMA buffer on underrun. Queue silence
 // after finite playback so the test tone cannot continue indefinitely.
 std::memset(tone_buffer_,0,audio_buffer_plan.bytes());for(std::size_t silent=0;silent<2048;silent+=audio_buffer_plan.frames){auto silence=write_pcm_unlocked(tone_buffer_,std::min(audio_buffer_plan.frames,std::size_t{2048}-silent));if(!silence)return silence;}vTaskDelay(pdMS_TO_TICKS(duration+20));samples_.suspend_output();
 // Keep the active-low amplifier awake between short UI tones. Powering it
 // down here made the next 10 ms click finish before the amplifier woke up.
 return core::Status::success();}
core::Status AudioDevice::request_tone(std::uint16_t hz,std::uint16_t duration,std::uint8_t volume){if(health_.state!=DeviceState::ready||!tone_task_)return {core::ErrorCode::unavailable,"audio worker unavailable"};requested_hz_=hz;requested_duration_ms_=duration;requested_volume_=volume;xTaskNotifyGive(static_cast<TaskHandle_t>(tone_task_));return core::Status::success();}
void AudioDevice::tone_worker_entry(void* context){static_cast<AudioDevice*>(context)->tone_worker();}
void AudioDevice::tone_worker(){while(tone_worker_running_){ulTaskNotifyTake(pdTRUE,portMAX_DELAY);if(!tone_worker_running_)break;(void)tone(requested_hz_.load(),requested_duration_ms_.load(),requested_volume_.load());}tone_task_=nullptr;vTaskDelete(nullptr);}
core::Status AudioDevice::write_pcm_unlocked(const std::int16_t* data,std::size_t frames){if(config_.pins.speaker>=0)gpio_set_level(static_cast<gpio_num_t>(config_.pins.speaker),0);return samples_.write_stereo(data,frames);}
core::Status AudioDevice::write_pcm(const std::int16_t* data,std::size_t frames){if(!tx_mutex_||xSemaphoreTake(static_cast<SemaphoreHandle_t>(tx_mutex_),portMAX_DELAY)!=pdTRUE)return {core::ErrorCode::unavailable,"audio output lock unavailable"};const auto result=write_pcm_unlocked(data,frames);xSemaphoreGive(static_cast<SemaphoreHandle_t>(tx_mutex_));return result;}
core::Status AudioDevice::read_pcm(std::int16_t* mono,std::size_t frames,std::size_t& frames_read,std::uint32_t timeout_ms){frames_read=0;if(!mono||frames>audio_buffer_plan.frames)return {core::ErrorCode::capacity_exceeded,"audio capture request exceeds scratch capacity"};if(const auto read=samples_.read_stereo(capture_buffer_,frames,frames_read,timeout_ms);!read)return read;for(std::size_t i=0;i<frames_read;++i)mono[i]=capture_buffer_[i*2];return core::Status::success();}
void AudioDevice::stop(){tone_worker_running_=false;if(tone_task_){xTaskNotifyGive(static_cast<TaskHandle_t>(tone_task_));for(int i=0;i<50&&tone_task_;++i)vTaskDelay(pdMS_TO_TICKS(1));if(tone_task_){vTaskDelete(static_cast<TaskHandle_t>(tone_task_));tone_task_=nullptr;}}if(config_.driver==board::AudioDriver::es8311&&config_.pins.speaker>=0)gpio_set_level(static_cast<gpio_num_t>(config_.pins.speaker),1);samples_.stop();if(tx_mutex_){vSemaphoreDelete(static_cast<SemaphoreHandle_t>(tx_mutex_));tx_mutex_=nullptr;}if(tone_buffer_){heap_caps_free(tone_buffer_);tone_buffer_=nullptr;}if(capture_buffer_){heap_caps_free(capture_buffer_);capture_buffer_=nullptr;}codec_.stop();if(config_.driver==board::AudioDriver::pwm)ledc_stop(LEDC_LOW_SPEED_MODE,LEDC_CHANNEL_1,0);health_.state=DeviceState::stopped;}
}
