#include "espscreen/hal/storage_device.hpp"
#include "espscreen/board/bus_host.hpp"
#include "driver/spi_master.h"
#include "driver/sdmmc_host.h"
#include "esp_err.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_vfs_fat.h"
#include "sdmmc_cmd.h"
namespace espscreen::hal { namespace { constexpr const char* TAG="Storage";spi_host_device_t host(std::int8_t index){return index==2?SPI2_HOST:SPI3_HOST;} }
StorageDevice::~StorageDevice(){stop();}
core::Status StorageDevice::start(){if(mount_policy_.mounted())return core::Status::success();if(config_.driver==board::StorageDriver::none){health_={DeviceState::degraded,core::ErrorCode::unsupported,"sd not configured"};return {core::ErrorCode::unsupported,"sd not configured"};}if(config_.driver==board::StorageDriver::sdspi&&!board::host_belongs_to(config_.host,board::BusFamily::spi))return {core::ErrorCode::invalid_argument,"SDSPI storage requires an SPI host"};if(config_.driver==board::StorageDriver::sdmmc&&!board::host_belongs_to(config_.host,board::BusFamily::sdmmc))return {core::ErrorCode::invalid_argument,"SDMMC storage requires an SDMMC host"};health_.state=DeviceState::starting;esp_vfs_fat_sdmmc_mount_config_t mount{};mount.format_if_mount_failed=false;mount.max_files=config_.max_files;mount.allocation_unit_size=16*1024;sdmmc_card_t* card=nullptr;esp_err_t err=ESP_FAIL;
 if(config_.driver==board::StorageDriver::sdspi){auto h=host(board::bus_index(config_.host));spi_bus_config_t bus{};bus.mosi_io_num=config_.pins.cmd;bus.miso_io_num=config_.pins.d0;bus.sclk_io_num=config_.pins.clk;bus.quadwp_io_num=-1;bus.quadhd_io_num=-1;bus.max_transfer_sz=4096;if(spi_bus_initialize(h,&bus,SPI_DMA_CH_AUTO)!=ESP_OK)return {core::ErrorCode::io_error,"sd spi bus initialization failed"};bus_initialized_=true;sdmmc_host_t sh=SDSPI_HOST_DEFAULT();sh.slot=h;sh.max_freq_khz=config_.clock_hz/1000;sdspi_device_config_t slot=SDSPI_DEVICE_CONFIG_DEFAULT();slot.gpio_cs=static_cast<gpio_num_t>(config_.pins.cs);slot.host_id=h;err=esp_vfs_fat_sdspi_mount(config_.mount_point,&sh,&slot,&mount,&card);}
 else {const bool four_bit=config_.pins.d1>=0&&config_.pins.d2>=0&&config_.pins.d3>=0;auto mount_sdmmc=[&](int width,std::uint32_t frequency){sdmmc_host_t sh=SDMMC_HOST_DEFAULT();sh.max_freq_khz=frequency/1000;sdmmc_slot_config_t slot=SDMMC_SLOT_CONFIG_DEFAULT();slot.width=width;slot.clk=static_cast<gpio_num_t>(config_.pins.clk);slot.cmd=static_cast<gpio_num_t>(config_.pins.cmd);slot.d0=static_cast<gpio_num_t>(config_.pins.d0);if(width==4){slot.d1=static_cast<gpio_num_t>(config_.pins.d1);slot.d2=static_cast<gpio_num_t>(config_.pins.d2);slot.d3=static_cast<gpio_num_t>(config_.pins.d3);}slot.flags|=SDMMC_SLOT_FLAG_INTERNAL_PULLUP;return esp_vfs_fat_sdmmc_mount(config_.mount_point,&sh,&slot,&mount,&card);};err=mount_sdmmc(four_bit?4:1,config_.clock_hz);if(err!=ESP_OK&&four_bit){ESP_LOGW(TAG,"4-bit SD mount failed (%s); retrying in 1-bit mode",esp_err_to_name(err));card=nullptr;err=mount_sdmmc(1,config_.clock_hz);}}
 if(err!=ESP_OK){if(bus_initialized_){spi_bus_free(host(board::bus_index(config_.host)));bus_initialized_=false;}mount_policy_.mount_failed(static_cast<std::uint64_t>(esp_timer_get_time()));health_={DeviceState::degraded,core::ErrorCode::unavailable,"sd card absent or mount failed"};ESP_LOGW(TAG,"SD mount failed at %s: %s; retrying",config_.mount_point,esp_err_to_name(err));return {core::ErrorCode::unavailable,"sd card absent or mount failed"};}card_=card;mount_policy_.mount_succeeded();health_={DeviceState::ready,core::ErrorCode::ok,"mounted"};ESP_LOGI(TAG,"SD card mounted at %s",config_.mount_point);return core::Status::success();}
void StorageDevice::stop(){if(mount_policy_.mounted()){esp_vfs_fat_sdcard_unmount(config_.mount_point,static_cast<sdmmc_card_t*>(card_));card_=nullptr;}if(bus_initialized_){spi_bus_free(host(board::bus_index(config_.host)));bus_initialized_=false;}mount_policy_.stop();health_.state=DeviceState::stopped;}
void StorageDevice::poll(){if(config_.driver==board::StorageDriver::none)return;const auto now=static_cast<std::uint64_t>(esp_timer_get_time());if(mount_policy_.should_attempt(now))(void)start();}
StorageStats StorageDevice::stats()const{StorageStats out{};out.mounted=mount_policy_.mounted();if(!out.mounted)return out;(void)esp_vfs_fat_info(config_.mount_point,&out.total_bytes,&out.free_bytes);return out;}
}
