#include "espscreen/hal/touch_device.hpp"
#include "espscreen/hal/touch_geometry.hpp"
#include "espscreen/hal/i2c_bus.hpp"
#include "espscreen/board/bus_host.hpp"
#include "driver/gpio.h"
#include "esp_rom_sys.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <algorithm>
#include <array>

namespace espscreen::hal {
TouchDevice::~TouchDevice(){stop();}
core::Status TouchDevice::start(){if(config_.driver==board::TouchDriver::none){health_={DeviceState::degraded,core::ErrorCode::unsupported,"touch not configured"};return {core::ErrorCode::unsupported,"touch not configured"};}health_.state=DeviceState::starting;
 if(config_.driver==board::TouchDriver::xpt2046){gpio_config_t out{};out.mode=GPIO_MODE_OUTPUT;out.pin_bit_mask=(1ULL<<config_.pins.sclk)|(1ULL<<config_.pins.mosi)|(1ULL<<config_.pins.cs);gpio_config(&out);gpio_set_level(static_cast<gpio_num_t>(config_.pins.cs),1);gpio_config_t in{};in.mode=GPIO_MODE_INPUT;in.pull_up_en=GPIO_PULLUP_ENABLE;in.pin_bit_mask=(1ULL<<config_.pins.miso)|(board::valid_pin(config_.pins.irq)?1ULL<<config_.pins.irq:0);gpio_config(&in);}
 else {if(!board::host_belongs_to(config_.host,board::BusFamily::i2c))return {core::ErrorCode::invalid_argument,"I2C touch requires an I2C host"};const auto port=board::bus_index(config_.host);auto status=i2c_.acquire(port,config_.pins.mosi,config_.pins.sclk,config_.clock_hz);if(!status){health_={DeviceState::degraded,status.code(),"touch i2c unavailable"};return status;}i2c_acquired_=true;if(board::valid_pin(config_.pins.reset)){gpio_set_direction(static_cast<gpio_num_t>(config_.pins.reset),GPIO_MODE_OUTPUT);gpio_set_level(static_cast<gpio_num_t>(config_.pins.reset),0);vTaskDelay(pdMS_TO_TICKS(100));gpio_set_level(static_cast<gpio_num_t>(config_.pins.reset),1);vTaskDelay(pdMS_TO_TICKS(100));}if(config_.driver==board::TouchDriver::cst328){std::uint8_t status_byte=0xFF,max_points=0;if(!i2c_.read16(port,0x55,0x0001,&status_byte,1)||!i2c_.read16(port,0x55,0x0009,&max_points,1)||max_points==0){health_={DeviceState::degraded,core::ErrorCode::unavailable,"CST328 touch probe failed"};return {core::ErrorCode::unavailable,"CST328 touch probe failed"};}maximum_touches_=std::min<std::uint8_t>(max_points,10);}}
 health_={DeviceState::ready,core::ErrorCode::ok,"ready"};return core::Status::success();}
void TouchDevice::stop(){if(i2c_acquired_){i2c_.release(board::bus_index(config_.host));i2c_acquired_=false;}health_.state=DeviceState::stopped;}
bool TouchDevice::read(TouchPoint& p){bool ok=config_.driver==board::TouchDriver::xpt2046?read_xpt2046(p):(config_.driver==board::TouchDriver::cst328?read_cst328(p):read_ft6336(p));if(ok)p=transform_touch_point(p,display_.width,display_.height,config_.rotation);return ok;}
std::uint8_t TouchDevice::soft_spi_transfer(std::uint8_t value){std::uint8_t in=0;for(int bit=7;bit>=0;--bit){gpio_set_level(static_cast<gpio_num_t>(config_.pins.mosi),(value>>bit)&1);gpio_set_level(static_cast<gpio_num_t>(config_.pins.sclk),1);esp_rom_delay_us(1);in=(in<<1)|gpio_get_level(static_cast<gpio_num_t>(config_.pins.miso));gpio_set_level(static_cast<gpio_num_t>(config_.pins.sclk),0);esp_rom_delay_us(1);}return in;}
std::uint16_t TouchDevice::xpt_read_axis(std::uint8_t command){soft_spi_transfer(command);const std::uint16_t hi=soft_spi_transfer(0),lo=soft_spi_transfer(0);return ((hi<<8)|lo)>>3;}
bool TouchDevice::read_xpt2046(TouchPoint& p){if(board::valid_pin(config_.pins.irq)&&gpio_get_level(static_cast<gpio_num_t>(config_.pins.irq))!=0){p.pressed=false;return true;}std::array<std::uint16_t,5> xs{},ys{};gpio_set_level(static_cast<gpio_num_t>(config_.pins.cs),0);for(int i=0;i<5;++i){xs[i]=xpt_read_axis(0xD0);ys[i]=xpt_read_axis(0x90);}gpio_set_level(static_cast<gpio_num_t>(config_.pins.cs),1);std::sort(xs.begin(),xs.end());std::sort(ys.begin(),ys.end());p.x=map_touch_axis(xs[2],config_.calibration[0],config_.calibration[1],display_.width);p.y=map_touch_axis(ys[2],config_.calibration[2],config_.calibration[3],display_.height);p.pressed=true;return true;}
bool TouchDevice::read_ft6336(TouchPoint& p){std::uint8_t buf[5]{};if(!i2c_.read(board::bus_index(config_.host),0x38,0x02,buf,sizeof(buf)))return false;const auto count=buf[0]&0x0F;if(count==0){p.pressed=false;return true;}p.x=((buf[1]&0x0F)<<8)|buf[2];p.y=((buf[3]&0x0F)<<8)|buf[4];p.pressed=true;return true;}
bool TouchDevice::read_cst328(TouchPoint& p){std::uint8_t update=0;if(!i2c_.read16(board::bus_index(config_.host),0x55,0x0010,&update,1))return false;if((update&0x08)==0){p.pressed=false;return true;}std::array<std::uint8_t,70> reports{};const auto length=static_cast<std::size_t>(maximum_touches_)*7;if(!i2c_.read16(board::bus_index(config_.host),0x55,0x0014,reports.data(),length))return false;const std::uint8_t* selected=nullptr;for(std::uint8_t i=0;i<maximum_touches_;++i){const auto* candidate=reports.data()+static_cast<std::size_t>(i)*7;const auto x=static_cast<std::uint16_t>(((candidate[0]&0x3F)<<8)|candidate[1]);const auto y=static_cast<std::uint16_t>(((candidate[2]&0x3F)<<8)|candidate[3]);if((candidate[0]&0x80)||(x<display_.width&&y<display_.height&&(x||y))){selected=candidate;break;}}if(!selected){p.pressed=false;return true;}p.x=((selected[0]&0x3F)<<8)|selected[1];p.y=((selected[2]&0x3F)<<8)|selected[3];p.pressed=true;return true;}
}
